Optional loading of unimod files
computational-ms/chemical-composition pull request #19
Opened 2021-08-03 09:07 UTC by gavswe

Added the capability to optionally load the default unimod files in unimod_parser.  This is now an initialisation parameter so can be controlled by external code calling chemical-composition

2021-08-03 13:14 UTC, StSchulze approved these changes

2021-08-06 12:52 UTC, MKoesters requested changes
Test are failing

` TypeError: __init__() got an unexpected keyword argument 'add_default_files'`

2021-08-16 08:20 UTC, gavswe commented
> 
> 
> Test are failing
> 
> ` TypeError: __init__() got an unexpected keyword argument 'add_default_files'`

OK this will be fixed in the pull request I made for unimod-mapper.

2021-08-18 08:14 UTC, MKoesters approved these changes

2021-08-20 12:22 UTC, merged